### ISSUE TITLE
Dumping

### ISSUE THREAD

**Issue by Droidem** [Cu3PO42/KeySAVe#137] opened 2016-11-13 01:33 UTC
When you filter by boxes and follow that with any of the exporting options, it dumps the entire game. I'm using Version 1.2.3.

**Comment by Cu3PO42** [comment] 2016-11-13 09:40
This is a duplicate of #136 and fixed in `master`. It will work properly again in the next version.

**Closed** 2016-11-13 09:41 UTC
Labels: bug, duplicate
